import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { NextIntlClientProvider } from 'next-intl'
import { ReactNode } from 'react'

import { LayoutContent } from '@/src/components/LayoutContent/LayoutContent'
import './globals.scss'

export const metadata: Metadata = {
  title: 'Mariion-dev',
  description: 'Generated by create next app'
}

type Props = {
  children: ReactNode
  params: { locale: string }
}

export default async function LocaleLayout(props: Props) {
  const { children, params } = props
  const { locale } = await params // ✅ await params avant d'accéder à ses propriétés

  const { locales } = await import('../../../i18n')

  if (!locale || !locales.includes(locale as any)) {
    notFound()
  }

  let messages
  try {
    messages = (await import(`../../../messages/${locale}.json`)).default
  } catch {
    notFound()
  }

  return (
    <html lang={locale}>
      <body suppressHydrationWarning={true}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <LayoutContent>{children}</LayoutContent>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
