import type { Metadata } from "next";
import "./globals.scss";

import { Header } from "@/src/components/Header/Header";
import { Footer } from "@/src/components/Footer/Footer";
import { NextIntlClientProvider } from "next-intl";
import frMessages from "../../../dictionnary/fr.json";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Mariion-dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const locale = "fr";
  const messages = frMessages;
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
